opt: fix link error.
Fix link errors caused by missing pthread library.

error message:
smtl.o: In function `smtl_thread_func(void*)':
smtl.cpp:(.text+0x63): undefined reference to `pthread_setaffinity_np'
smtl.o: In function `smtl_init(smtl_t**, std::vector<int, std::allocator<int> >&)':
smtl.cpp:(.text+0x3b8): undefined reference to `pthread_create'
smtl.o: In function `smtl_fini(smtl_t*)':
smtl.cpp:(.text+0x577): undefined reference to `pthread_join'
collect2: error: ld returned 1 exit status